#!/usr/bin/env bash
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
THEMES_DIR="$DOTFILES_DIR/themes"

if [ $# -eq 0 ]; then
    echo "Usage: ./switch-theme.sh <theme>"
    echo ""
    echo "Available themes:"
    for dir in "$THEMES_DIR"/*/; do
        name="$(basename "$dir")"
        desc="$(head -1 "$dir/theme.sh" | sed 's/^# *//')"
        echo "  $name  —  $desc"
    done
    exit 0
fi

THEME="$1"
THEME_DIR="$THEMES_DIR/$THEME"
THEME_FILE="$THEME_DIR/theme.sh"

if [ ! -f "$THEME_FILE" ]; then
    echo "Error: theme '$THEME' not found"
    echo "Run without arguments to list available themes."
    exit 1
fi

source "$THEME_FILE"

# --- SketchyBar ---
cat > "$DOTFILES_DIR/sketchybar/colors.sh" << EOF
#!/bin/bash
# Theme: $THEME (auto-generated by switch-theme.sh)

export WHITE=$TEXT_COLOR
export BAR_COLOR=$BAR_COLOR
export ITEM_BG_COLOR=$ITEM_BG_COLOR
export ACCENT_COLOR=$ACCENT_COLOR
export BRACKET_BG_COLOR=$BRACKET_BG_COLOR
EOF

if command -v sketchybar &>/dev/null; then
    sketchybar --reload
    echo "SketchyBar: reloaded"
fi

# --- Cursor / VSCode ---
SETTINGS="$DOTFILES_DIR/cursor/settings.json"
sed -i '' "s/\"workbench\.colorTheme\": \".*\"/\"workbench.colorTheme\": \"$CURSOR_THEME\"/" "$SETTINGS"

if [ -n "${CURSOR_EXTENSION:-}" ] && command -v cursor &>/dev/null; then
    cursor --install-extension "$CURSOR_EXTENSION" --force 2>/dev/null &
fi
echo "Cursor: $CURSOR_THEME"

# --- iTerm2 ---
for ITERMCOLORS in "$THEME_DIR"/*.itermcolors; do
    [ -f "$ITERMCOLORS" ] || continue
    PRESET_NAME="$(basename "$ITERMCOLORS" .itermcolors)"
    if /usr/libexec/PlistBuddy -c "Print ':Custom Color Presets:$PRESET_NAME'" ~/Library/Preferences/com.googlecode.iterm2.plist &>/dev/null; then
        echo "iTerm2: '$PRESET_NAME' already imported"
    else
        open "$ITERMCOLORS"
        echo "iTerm2: imported '$PRESET_NAME' (select it in Settings > Profiles > Colors > Color Presets)"
    fi
    break
done

# --- Chrome ---
if [ -n "${CHROME_THEME_URL:-}" ]; then
    open "$CHROME_THEME_URL"
    echo "Chrome: opened theme page (click 'Add to Chrome' if not installed)"
fi

wait 2>/dev/null
echo "Done — switched to '$THEME'"
