#!/bin/bash
# Theme: gruvbox (auto-generated by switch-theme.sh)

export WHITE=0xffebdbb2
export BAR_COLOR=0xff282828
export ITEM_BG_COLOR=0xff3c3836
export ACCENT_COLOR=0xfffabd2f
export BRACKET_BG_COLOR=0xaa1d2021
