#!/bin/bash
# Theme: gruvbox (auto-generated by switch-theme.sh)

# Colors
export WHITE=0xffebdbb2
export BAR_COLOR=0x00ffffff
export ITEM_BG_COLOR=0xff3c3836
export ACCENT_COLOR=0xfffabd2f
export BRACKET_BG_COLOR=0xaa1d2021

# Fonts
export FONT="Fira Code"
export NERD_FONT="FiraCode Nerd Font Mono"
export APP_FONT="sketchybar-app-font"

# Font sizes
export ICON_SIZE="17.0"
export ICON_SIZE_LG="20.0"
export ICON_SIZE_XL="25.0"
export LABEL_SIZE="14.0"
export LABEL_SIZE_SM="10.0"
export LABEL_SIZE_XS="9.0"

# Geometry
export BRACKET_HEIGHT=28
export BRACKET_RADIUS=12
export ITEM_PADDING=8
export BAR_HEIGHT=37
