#!/bin/bash

BORDERS_DIR="$HOME/.config/borders"

source "$BORDERS_DIR/colors.sh"

options=(
    style=round
    width=6.0
    hidpi=on
    active_color=$BORDER_ACTIVE_COLOR
    inactive_color=0x00000000
)

borders "${options[@]}"
